### ISSUE TITLE
gre's TODO

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-vault-front#14]
- [x] make that the Currency formatting nb of digits of crypto will depends on the actual value so big value won't print digits and low value will print more digits. can use Math.log10
- [x] Rethink the way we would calculate countervalues. Shouldn't we have the countervalues within the currencies so we can just calculate them all clientside and don't need them everywhere? `<CounterValue value={} currency={} counterCurrency={} />`
- [x] investigate how we can impl Modal by just rendering from anywhere and so it also handle the body blur, we can pass-in data/any props directly and don't need redux.
- [ ] port some existing modals. hopefully we should be able to accumulate routes so we have all needed context (our route is our state: for instance if you open a op from /accounts/0 it will go to /accounts/0/operations/XXX and we have the full history to display the popup on top of account (actually it should directly maps to components & react-router v4 code).
- [x] we assume user is connected if token is here, but we need to recover the case it is wrong (server need to give a specific HTTP code?).
- [x] Implement a generic CardLink for the VIEW ALL things and we can connect to the actual thing
- [x] Rethink the dashboard API, each card may be independently connected & we could have different APIs. discuss with API people
- [ ] implement the Pending Requests (2) indicator (connected component)
- [x] App root component won't need to be connected to redux, only specific leaf components might be
- [x] Implement a generic action button that would wait a promise (and set a pending class)
®

**Comment by flocks** [comment]
Nice! Good luck with that :)

One thing we also need to think about is how we handle alert messages. Currently there is a redux module listening to events that needs an alert to be displayed. There is also an AlertContainer connected to this store, and which renders the Alerts components. 

The new data fetching paradigm kinda breaks it because we are only dispatching `DATA_FETCHED` for every API calls. We need to find a clever way to handle this. May be we could dispatch a `type` alongside with `DATA_FETCHED` representing the resource we just got/updates/deleted ? Or should the components be responsible for triggering an alert after the `Promise` succeeded or failed ?

**Comment by gre** [comment]
yeah I guess we can try one or the other solution, or both. new data fetching paradigm should allow both. if we really want systematic alert messages over all http calls, the first will be easier (might need to send more things in that DATA_FETCHED, might need to have something like a DATA_FETCH_FAIL too). I see that redux is typically to solve this easily (because alert container is something living somewhere else and wanna listen to all events).

If we want very specific other notifs, we might need to think it differently however, like the way you render `<Snackbar>` from anywhere. we just probably don't want to do this in all components but solve it once like it was done before ;)
